name: Feature Preview
description: 🏗️ GitHub Action for deploying feature previews.

inputs:
  feature-name:
    description: "The name of the feature to deploy."
    required: true

  cloudflare-email:
    description: "The email address for Cloudflare."
    required: true

  cloudflare-api-key:
    description: "The API key for Cloudflare."
    required: true

  cloudflare-domain:
    description: "The domain to deploy the feature preview to."
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Test
      uses: ./action
      with:

    - name: Deploy
      uses: saturdayshdev/deploy-action@v1.2.2
      with:
